[package]
name = "festerm"
version = "0.1.0"
authors = ["agatan <agatan039@gmail.com>"]

[dependencies]
nix = "*"
term = "*"
libc = "*"
signal-notify = "0.1.2"
unicode-width = "*"
num = "0.1"
num-derive = "*"
